common:
  lid_topic: "/velodyne_points"  # lid_topic: "/velodyne_points" "/livox/lidar"
  imu_topic: "/imu/data"        # imu_topic: "/handsfree/imu" "/livox/imu"
    
preprocess:
  lidar_type: 2     # lidar_type: 2     1           #1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for L515 LiDAR
  scan_line: 16      # scan_line: 64 #livox 6  #velodyne 64
  blind: 0.2
  point_filter_num: 1
  calib_laser: false              # true for KITTI Odometry dataset

mapping:
  down_sample_size: 0.1
  max_iteration: 3
  voxel_size: 0.5  #usedtobe 3.0 #nowcanbe0.5 #0.375
  plannar_threshold: 0.01
  max_points_size: 100
  update_size_threshold: 5
  sigma_num: 3

noise_model:
  ranging_cov: 0.02
  angle_cov: 0.1
  acc_cov_scale: 1.0
  gyr_cov_scale: 0.5

imu:
  imu_en: true
  extrinsic_T: [0.08, 0.029, 0.03]
  extrinsic_R: [0.999945562,  0.009074807,  0.005149763,
               -0.009060897,  0.999955255, -0.002718066,
               -0.005174199,  0.002671256,  0.999983046]

visualization:
  pub_voxel_map: false
  pub_voxel_map_period: 50
  pub_point_cloud: false
  dense_map_enable: false
  pub_point_cloud_skip: false             # publish one points per five points

Result:
  write_kitti_log: false
  result_path: "/home/ycj/catkin_github/src/VoxelMapPlus/Log/kitt_log.txt"
